sonar.projectKey=cochera-mysql_2
sonar.projectName=cochera-mysql_2
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.token=squ_93bd91d229aa845286bd3eb7d055914299111c26

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/vendor/**,**/node_modules/**,**/.idea/**,**/storage/**